server:
  port: 3020

spring:
  dubbo:
    application:
      name: xxpay4dubbo-web
    registry:
      address: zookeeper://localhost:2181
    scan: org.xxpay.dubbo

logging:
  file: D:/log/pay//xxpay4dubbo-web.log